# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('introduction', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=11)),
                ('wechat', models.TextField(max_length=30)),
                ('accpted', models.BooleanField(default=False)),
            ],
        ),
    ]
