# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='accpted',
            field=models.IntegerField(default=0),
        ),
    ]
