# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20170303_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='accpted',
            field=models.BooleanField(default=False),
        ),
    ]
