# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20170303_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='accpted',
        ),
        migrations.AddField(
            model_name='wish',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
    ]
